/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pzybrick.iote2e.schema.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum operation {
  SENSOR_VALUES, ACTUATOR_CONFIRM, LOOPBACK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"operation\",\"namespace\":\"com.pzybrick.iote2e.schema.avro\",\"symbols\":[\"SENSOR_VALUES\",\"ACTUATOR_CONFIRM\",\"LOOPBACK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
