/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pzybrick.iote2e.schema.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SensorValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1721305798952042694L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorValue\",\"namespace\":\"com.pzybrick.iote2e.schema.avro\",\"fields\":[{\"name\":\"sensor_name\",\"type\":\"string\"},{\"name\":\"sensor_value\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence sensor_name;
  @Deprecated public java.lang.CharSequence sensor_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensorValue() {}

  /**
   * All-args constructor.
   * @param sensor_name The new value for sensor_name
   * @param sensor_value The new value for sensor_value
   */
  public SensorValue(java.lang.CharSequence sensor_name, java.lang.CharSequence sensor_value) {
    this.sensor_name = sensor_name;
    this.sensor_value = sensor_value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor_name;
    case 1: return sensor_value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor_name = (java.lang.CharSequence)value$; break;
    case 1: sensor_value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sensor_name' field.
   * @return The value of the 'sensor_name' field.
   */
  public java.lang.CharSequence getSensorName() {
    return sensor_name;
  }

  /**
   * Sets the value of the 'sensor_name' field.
   * @param value the value to set.
   */
  public void setSensorName(java.lang.CharSequence value) {
    this.sensor_name = value;
  }

  /**
   * Gets the value of the 'sensor_value' field.
   * @return The value of the 'sensor_value' field.
   */
  public java.lang.CharSequence getSensorValue() {
    return sensor_value;
  }

  /**
   * Sets the value of the 'sensor_value' field.
   * @param value the value to set.
   */
  public void setSensorValue(java.lang.CharSequence value) {
    this.sensor_value = value;
  }

  /**
   * Creates a new SensorValue RecordBuilder.
   * @return A new SensorValue RecordBuilder
   */
  public static com.pzybrick.iote2e.schema.avro.SensorValue.Builder newBuilder() {
    return new com.pzybrick.iote2e.schema.avro.SensorValue.Builder();
  }

  /**
   * Creates a new SensorValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensorValue RecordBuilder
   */
  public static com.pzybrick.iote2e.schema.avro.SensorValue.Builder newBuilder(com.pzybrick.iote2e.schema.avro.SensorValue.Builder other) {
    return new com.pzybrick.iote2e.schema.avro.SensorValue.Builder(other);
  }

  /**
   * Creates a new SensorValue RecordBuilder by copying an existing SensorValue instance.
   * @param other The existing instance to copy.
   * @return A new SensorValue RecordBuilder
   */
  public static com.pzybrick.iote2e.schema.avro.SensorValue.Builder newBuilder(com.pzybrick.iote2e.schema.avro.SensorValue other) {
    return new com.pzybrick.iote2e.schema.avro.SensorValue.Builder(other);
  }

  /**
   * RecordBuilder for SensorValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorValue>
    implements org.apache.avro.data.RecordBuilder<SensorValue> {

    private java.lang.CharSequence sensor_name;
    private java.lang.CharSequence sensor_value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pzybrick.iote2e.schema.avro.SensorValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor_name)) {
        this.sensor_name = data().deepCopy(fields()[0].schema(), other.sensor_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sensor_value)) {
        this.sensor_value = data().deepCopy(fields()[1].schema(), other.sensor_value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SensorValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pzybrick.iote2e.schema.avro.SensorValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sensor_name)) {
        this.sensor_name = data().deepCopy(fields()[0].schema(), other.sensor_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sensor_value)) {
        this.sensor_value = data().deepCopy(fields()[1].schema(), other.sensor_value);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sensor_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getSensorName() {
      return sensor_name;
    }

    /**
      * Sets the value of the 'sensor_name' field.
      * @param value The value of 'sensor_name'.
      * @return This builder.
      */
    public com.pzybrick.iote2e.schema.avro.SensorValue.Builder setSensorName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sensor_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_name' field has been set.
      * @return True if the 'sensor_name' field has been set, false otherwise.
      */
    public boolean hasSensorName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor_name' field.
      * @return This builder.
      */
    public com.pzybrick.iote2e.schema.avro.SensorValue.Builder clearSensorName() {
      sensor_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sensor_value' field.
      * @return The value.
      */
    public java.lang.CharSequence getSensorValue() {
      return sensor_value;
    }

    /**
      * Sets the value of the 'sensor_value' field.
      * @param value The value of 'sensor_value'.
      * @return This builder.
      */
    public com.pzybrick.iote2e.schema.avro.SensorValue.Builder setSensorValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sensor_value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_value' field has been set.
      * @return True if the 'sensor_value' field has been set, false otherwise.
      */
    public boolean hasSensorValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sensor_value' field.
      * @return This builder.
      */
    public com.pzybrick.iote2e.schema.avro.SensorValue.Builder clearSensorValue() {
      sensor_value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public SensorValue build() {
      try {
        SensorValue record = new SensorValue();
        record.sensor_name = fieldSetFlags()[0] ? this.sensor_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sensor_value = fieldSetFlags()[1] ? this.sensor_value : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
